refactored (version : 1.0)
Star-Academy/Summer1401-SE-Team02 pull request #1
Opened 2022-07-19 13:27 UTC by Soltaniant

ready to check functionality and clean code.
@abolfazlghalandary

2022-07-19 14:09 UTC, abolfazlghalandary commented on Main.java
> -import java.io.File;
از این به بعد اسم برنچا رو کباب کیس بزن
https://stackoverflow.com/questions/273695/what-are-some-examples-of-commonly-used-practices-for-naming-git-branches

2022-07-19 14:09 UTC, abolfazlghalandary commented on src/Normalizer.java
> +    private static ArrayList<String> removeStopWords(ArrayList<String> words) {
ی ریفرمت بزن حتما

2022-07-19 14:09 UTC, abolfazlghalandary commented on src/SearchEngine.java
> +     private static void insertDocID(String word, ArrayList<Integer> docsIDs, int docID){
Id
کلمات مختصر فقط حرف اول Upper باشه

2022-07-19 14:11 UTC, abolfazlghalandary approved these changes

2022-07-20 06:54 UTC, mohammadhheidarzade requested changes

2022-07-20 06:54 UTC, mohammadhheidarzade commented on Main.java
> +          View.run();
متد های مربوط به خواندن فایل در کلاسی جداگانه نگه داری شود
بعد از جدا سازی مشاهده میشه این کلاس به SearchEngine وابستگی خواهد داشت
کلاس مربوط به خواندن فایل فقط فایل هارو برمیگردونه
یه کلاس داشته باشین که یک فایل بگیره و توکن ها فایل رو دریافت کنه
و بعد این توکن ها به کلاس SearchEngine داده بشه برای ایندکس کردن توکن ها

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/Database.java
> +     private static final String DATA_FOLDER = "Docs";
static ها موجودات خطرناکی هستند. درستش کنید اینو

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/Database.java
> +     private static final String DATA_FOLDER = "Docs";
این به صورت ورودی به کلاس داده شود.
همین docs رو در کلاس main هم استفاده کردین. معمولا این چیزا به عنوان کانفیگ ذخیره میشه و مقدارش از کانفیگ خونده میشه
اگر بخواین اسم پوشرو عوض کنید باید کل پروژرو بگردین ببینین کجا ها استفاده کردینش

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/Database.java
> +               SearchEngine.addFile(loadFile(file), file.getName());
کلاس دیتابیس نباید به SearchEngine وابستگی داشته باشه

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/Normalizer.java
> +    static private final ArrayList<String> stopWords = new ArrayList<String>(Arrays.asList("OURSELVES", "HERS", "BETWEEN", "YOURSELF", "BUT", "AGAIN", "THERE", "ABOUT", "ONCE", "DURING", "OUT", "VERY
این لیست به صورت ورودی گرفته بشه
ضمن اینکه تمام فیلدها و متدهای static باید از این حالت دربیان

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/OrderedSet.java
> +public class OrderedSet {
چه قدر این کلاس نا مرتبه. reformat کنید

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/Query.java
> +     public boolean isEnd(){
این باید در کلاس main هندل بشه. نه اینجا

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/enums/ColorCodes.java
> +public enum ColorCodes {
این کلاس چی کار میکنه دقیقا؟

2022-07-20 06:54 UTC, mohammadhheidarzade commented on src/View.java
> +          while (!(query = new Query(scanner.nextLine())).isEnd()){
این باید توی main هندل بشه

2022-07-20 07:15 UTC, Soltaniant commented on src/enums/ColorCodes.java
> +public enum ColorCodes {
این کلاس کلا کار خاصی نمیکنه و با لاجیک کاری نداره. یه enum از رنگ هاست که بعدا توی کلاس view موقع چاپ کردن جواب استفاده میشه. فقط برای زیبایی بیشتره. اگر ران بگیرین متوجه میشین.
ولی در کل به سمت UI مربوط میشه

2022-07-20 07:57 UTC, Soltaniant commented on src/Normalizer.java
> +    static private final ArrayList<String> stopWords = new ArrayList<String>(Arrays.asList("OURSELVES", "HERS", "BETWEEN", "YOURSELF", "BUT", "AGAIN", "THERE", "ABOUT", "ONCE", "DURING", "OUT", "VERY
اصلاح شد، اما برای هردومون سواله. این لیست همواره ثابته. اما اگر قرار باشه استاتیک تعریف نکنیم. هر بار باید دوباره ساخته بشه که خب چون ثابته همیشه، دوباره ساختنش بیهوده به نظر میرسه و فقط زمان لود رو اضافه میکنه.
ممنون میشم در مورد اینکه چرا استاتیک ها رو خطرناک عنوان کردین توضیح بدین

2022-07-20 10:57 UTC, smhh22 commented
تست

2022-07-20 11:59 UTC, smhh22 commented on src/Normalizer.java
> +                                Constants.STOPPING_WORDS.toString().toUpperCase().split(Constants.SPACE.toString()))));
طولانی‌بودن این assignmentی که ایجاد شده و ۴ خطه باعث میشه فهم اینکه این تکه کد قراره چیکار کنه یه مقدار پیچیده شه به نظرم

2022-07-20 11:59 UTC, smhh22 commented on src/Normalizer.java
> +        return tokenized;
return new ArrayList(Arrays.asList(text.split("\\s+")));
جواب نمیده؟

2022-07-20 11:59 UTC, smhh22 commented on src/Normalizer.java
> +    }
A.removeAll(B)
از removeStopWords(A, B) کوتاهتره و نیازی به ساخت متد جدید نبود.
هر چند چون اونجوری دیگه void میشه مجبور میشید اون ورودی‌هاش رو قبلش بسازید و بریزید تو یه متغیر که خب این هم باعث میشه ایرادی که ۲ تا کامنت بالاتر بگیرم تا یه حدی رفع بشه.

2022-07-20 11:59 UTC, smhh22 commented on src/SearchEngine.java
> +               insertDocID(word, indexedData.get(word), docID);
اینجا چرا از indexedData.get(word).add(docID) استفاده نکردید؟

2022-07-20 11:59 UTC, smhh22 commented on src/enums/Constants.java
> +     SIMPLE_WORDS_REGEX("(?<!\\S)"),
این رجکسو نفهمیدم
درسته؟

2022-07-20 12:09 UTC, aliEm2001 commented on src/View.java
> +     private static void _error(String message) {
این قاعده ی نام گذاری رو جایی دیدین که اول اسم تابع _ بیاد؟

2022-07-20 12:09 UTC, aliEm2001 commented on src/View.java
> +          System.out.println(String.format(Constants.SUCCESS_MESSAGE.toString(), output.size(), output));
اینجا هم همینطور

2022-07-20 12:21 UTC, smhh22 requested changes
این کامنتایی که دادم رو Request changes نزده بودم :)

2022-07-20 12:57 UTC, Soltaniant commented on src/Normalizer.java
> +        return tokenized;
درست میگی

2022-07-20 13:01 UTC, Soltaniant commented on src/Normalizer.java
> +    }
قبلتر، اون لیست استاپینگ ووردز توی یه فیلد استاتیک بود. آقای حیدرزاده ایراد گرفتن که باید توی آرگومان تابع پاس بدیمش و ما هم اینجوریش کردیم. سر جلسه هم یه اشاره ای بهش کردم که ابوالفضل دلیلش رو گفت.
دلیل جداسازیش هم این بود که اولش قرار بود سیستم حذف کلمات اضافه سنگین تر از فعلی باشه.

2022-07-20 13:03 UTC, Soltaniant commented on src/enums/Constants.java
> +     SIMPLE_WORDS_REGEX("(?<!\\S)"),
اون آخری به این معنیه که قبل از یک کلمه، نباید کاراکتری به جز اسپیس باشه. یعنی یک کلمه واقعا تنها بدون + - قبلش

2022-07-20 13:03 UTC, Soltaniant commented on src/View.java
> +     private static void _error(String message) {
ما که ندیدیم :)

2022-07-20 13:04 UTC, Soltaniant commented on src/View.java
> +          System.out.println(String.format(Constants.SUCCESS_MESSAGE.toString(), output.size(), output));
چشم بزرگمرد

2022-07-20 13:08 UTC, Soltaniant commented on src/Normalizer.java
> +                                Constants.STOPPING_WORDS.toString().toUpperCase().split(Constants.SPACE.toString()))));
راستش ایده ای ندارم که در این مورد چه باید کرد. ولی یکم دنبال کنی خط رو معلوم میشه
ممنون بابت دقتت

2022-07-20 13:10 UTC, Soltaniant commented on src/SearchEngine.java
> +               insertDocID(word, indexedData.get(word), docID);
فرایند اصلی اضافه کردن شماره داک به لیست متفاوته. که البته ما فرایند اصلیش رو پیاده نکردیم. ولی از طرفی هم قبل از اضافه کردن باید حواست باشه که کد تکراری اضافه نکنی! (ما arraylist داریم)

2022-07-20 13:16 UTC, smhh22 approved these changes

2022-07-21 14:03 UTC, mohammadhheidarzade approved these changes

2022-07-22 12:20 UTC, aliEm2001 approved these changes

2022-07-22 12:27 UTC, merged