Tdd
Star-Academy/Summer1401-SE-Team02 pull request #5
Opened 2022-07-31 06:48 UTC by Soltaniant

initial project ...

2022-08-01 05:39 UTC, ali-bonaftizadeh reviewed
سلام و خداقوت، به شخصه از کدتون لذت بردم، هم از نظر تمیزی و خوانایی هم از نظر اصول سالید.

فقط یه نکته اینکه به نظر میاد کلاس SearchEngine داره SRP رو نقض میکنه. مثلا بهتر نبود کار ProcessQuery رو یه کلاس دیگه به صورت مجزا انجامش بده و تنها کار SearchEngine ؟این باشه که کوئری پردازش شده رو سرچ کنه

2022-08-01 10:20 UTC, abolfazlghalandary requested changes

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary.Test/NormalizerTest.cs
> +        //TODO: think about extension methods. is it true to use them here or not?
اینا نرن توی مستر ی وقت

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary.Test/NormalizerTest.cs
> +        result.Should().Equal(new List<string>() { "simple", "space", "seperated", "sentence" });
به صورت یک متغیر استخراج شده و در مرحله arrange قرار داده شود.

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary.Test/NormalizerTest.cs
> +        result.Should().Equal(new List<string>() { "simple", "space", "seperated", "sentence" });
خط قبل و باقی تست ها هم همینطور

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary.Test/NormalizerTest.cs
> +        var result = _basicNormalizer.RemoveStoppingWords("this is a test for removing stopping words");
inline data

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary.Test/QueryTest.cs
> +        var result = new SingleWordQuery(singleWord).GetMustIncludingWords();
مراحل AAA رعایت شود.
استخراج متغیر منجر ب خوانایی بیشتر تست خواهد شد.

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary.Test/QueryTest.cs
> +        var result = new SingleWordQuery(singleWord).GetMustIncludingWords();
باقی تست ها هم رعایت شود...

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary/DataProviding/Data.cs
> +public class Data : IData
رکورد شود و از auto property استفاده شود.

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary/DataProviding/IData.cs
> +public interface IData
فایده IData چیه؟

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary/Queries/IQuery.cs
> +    public List<string> GetMustIncludingWords();
طراحی جالبی نیس
هنگام نیاز ب اپراتور جدید مجبور ب تغییر این اینترفیس خواهیم شد

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary/Queries/IQuery.cs
> +    public List<string> GetMustIncludingWords();
که در نتیجه باید تمام پیاده سازی ها تا آن لحظه دوباره بازنویسی شوند.

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary/Queries/SingleWordQuery.cs
> +using System.Reflection.Metadata.Ecma335;
؟

2022-08-01 10:20 UTC, abolfazlghalandary commented on SampleLibrary/SearchEngine.cs
> +    public void ImportDataProviderData(IDataProvider dataProvider)
SRP...

2022-08-01 11:08 UTC, Soltaniant commented on SampleLibrary/DataProviding/IData.cs
> +public interface IData
that the interface for saving each single data. later in CICD classlib project it is the interface used for importing data to search engine.

2022-08-02 11:05 UTC, aliEm2001 requested changes

2022-08-02 11:05 UTC, aliEm2001 commented on SampleLibrary.Test/model/Data.cs
> +    public string _content { get; set; }
با توجه به اینکه این دوتا property هستند، نامگذاریشون باید PascalCase باشه

2022-08-02 11:05 UTC, aliEm2001 commented on SampleLibrary.Test/model/Data.cs
> +    public string GetContent() => _content;
وجود این دوتا هم فکر نمی کنم لازم باشه (چون source و  content پابلیک هستند)

2022-08-02 11:24 UTC, smhh22 requested changes
فکر کنم gitignoreت اشتباه شده باشه چون فایلای bin و obj تعداد زیادیشون اینجا هستن

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/NormalizerTest.cs
> +    }
حالا نکته مهمی نیست ولی نوع کوئری جوریه که به نظرم نیازی به حذف کردن stopping wordها نیست.
اگه بدون + و - مثلا بده خب منظورش اینه که اون is حتما باید تو اون فایله باشه دیگه

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/NormalizerTest.cs
> +    #region Normailizing a text (mixture of other three methods)
این integration test نیست؟

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/QueryTest.cs
> +    }
به نظرم اگه expected هم ورودی داده میشد منطقی‌تر بود.
چو الان عملا برای درآوردن expected احتمالا دوباره همون محتویات خود متد استفاده شده.

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/QueryTest.cs
> +    }
و تست‌های بعدی

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/model/MultipleWordsQuery.cs
> +}
اینا مگه منطق لایبراری نیستن؟
تو پروژه test چیکار میکنن؟

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/model/SingleWordQuery.cs
> +}
درک نکردم این کلاسو

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
> +[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETCoreApp,Version=v6.0", FrameworkDisplayName = "")]
gitignore

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary.Test/obj/Debug/net6.0/SampleLibrary.Test.AssemblyInfo.cs
> +//------------------------------------------------------------------------------
اینم همینطور

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary/Normalizing/BasicNormalizer.cs
> +                Regex.Replace(current, $"\\b{stoppingWord}\\b", string.Empty, RegexOptions.IgnoreCase));
ابن چیکار میکنه؟

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary/SearchEngine.cs
> +    }
open/close نیست

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary/SearchEngine.cs
> +    }
حالا اگه هندلر و اینترفیس و اینا نزدی هم لااقل توابع جدا بزن برای هر کدوم از این کارا به نظرم.

2022-08-02 11:24 UTC, smhh22 commented on SampleLibrary/enums/Constants.cs
> +    public static readonly string NegativeWordsRegex = "-(.*)";
احسنت

2022-08-04 04:30 UTC, Soltaniant commented on SampleLibrary/Normalizing/BasicNormalizer.cs
> +                Regex.Replace(current, $"\\b{stoppingWord}\\b", string.Empty, RegexOptions.IgnoreCase));
کلیتش اینه که داره کلمات stopping words رو از یه رشته پاک میکنه. در مورد اینکه چرا به این شکل نوشته شده هم باید بگم که اولش خیلی ساده نوشته بودم ولی خود IDE پیشنهاد داد اینجوری بنویسم :)

2022-08-04 06:54 UTC, abolfazlghalandary requested changes

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary.Test/SearchEngineTest.cs
> +        var result = _searchEngine.Search(createFakeQuery("simple"));
IDE warning nadad?

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary.Test/SearchEngineTest.cs
> +        result.Should().Equal(new List<string>() { "source1" });
AAA
رو بعضی منتورا میگن با کامنت جدا کنین جا بیفته براتون
کامنت نمیزنی حداقل قاعده اش رو رعایت کن:)

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary.Test/SearchEngineTest.cs
> +        result.Should().Equal(new List<string>() { "source1" });
╰（‵□′）╯

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary.Test/SearchEngineTest.cs
> +    private IQuery createFakeQuery(string query)
╰（‵□′）╯

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary.Test/model/Data.cs
> +// using SampleLibrary.DataProviding;
؟

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary.Test/model/Query.cs
> +// using SampleLibrary.Queries;
؟

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary.sln.DotSettings.user
> +﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
نیاد توی ریپو

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/DataProviding/IData.cs
> +public interface IData
قانع نشدم. صحبت کنیم

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/Normalizing/BasicNormalizer.cs
> +        text = Constants.StoppingWords.Split().Aggregate(text,
این نیاز نیس هر بار انجام شه.
به عنوان ی فیلد استاتیک ریدآنلی استخراج شه بهتره

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/Queries/IQuery.cs
> +    public string GetContent();
کاربرد؟

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/QueryProcessors/ChainQueryHandler.cs
> +        List<int> allDocIds);
SortedSet<int>> indexedData, List<int> allDocIds
مفهومشون خیلی نزدیکه. به عنوان ی کلاس استخراج شه قابل فهم تره

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/QueryProcessors/DefaultQueryProcessor.cs
> +    }
reformat whole solution

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/SearchEngine.cs
> +        _queryProcessor = new DefaultQueryProcessor();
ورودی کانستراکتور چرا نیس؟

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/SearchEngine.cs
> +    public void IndexData(IData data)
SRP?

2022-08-04 06:54 UTC, abolfazlghalandary commented on SampleLibrary/enums/Constants.cs
> +    public static readonly string StoppingWords =
const 
نمیشه کرد؟

2022-08-04 08:27 UTC, Soltaniant commented on SampleLibrary.Test/SearchEngineTest.cs
> +        var result = _searchEngine.Search(createFakeQuery("simple"));
nope! 
I don't know what you exactly mean, but I reformat it.

2022-08-04 09:41 UTC, abolfazlghalandary commented on SampleLibrary.Test/SearchEngineTest.cs
> +        var result = _searchEngine.Search(createFakeQuery("simple"));
createFakeQuery
اسم تابع PascalCaseعه

2022-08-04 09:48 UTC, abolfazlghalandary commented on app/SchoolContext.cs
> +namespace app;
؟

2022-08-04 10:37 UTC, abolfazlghalandary approved these changes
یه سری تغییرات ریز مونده بود که انجام بدی اوکی میشه.
دمت گرم عالی

2022-08-09 10:04 UTC, heidarzade-mh approved these changes

2022-08-09 10:04 UTC, heidarzade-mh commented on SampleLibrary/enums/Constants.cs
> +namespace SampleLibrary.enums;
چرا اسم پوشه ای که این فایل داخلش هست enums هست؟

2022-08-09 10:04 UTC, heidarzade-mh commented on SampleLibrary/SearchEngine.cs
> +
یک خط اضافه

2022-08-09 10:04 UTC, heidarzade-mh commented on SampleLibrary/QueryProcessors/ChainQueryHandler.cs
> +        return next;
return Next = next;

2022-08-09 12:48 UTC, Soltaniant commented on SampleLibrary/enums/Constants.cs
> +namespace SampleLibrary.enums;
قبلا یه سری اینام توش بود. اسمش رو یاد رفته بود عوض کنم

2022-08-09 13:00 UTC, merged