Phase#8 e fcore
Star-Academy/Summer1401-SE-Team02 pull request #7
Opened 2022-08-10 09:12 UTC by Soltaniant

2022-08-12 06:40 UTC, smhh22 reviewed
من از ابوالفضل که پرسیده بودم میگفت باید دوتا پروژه جدا بزنیم. یکی برای آپدیت کردن دیتابیس با اطلاعات json، یکی هم هندل کردن کوئری.
حالا میخوای از خود ابوالفضل بپرس

2022-08-12 06:40 UTC, smhh22 commented on app/controller/Program.cs
> +        var studentManagementSystem = new StudentManagementSystem { Database = database };
فکر کنم خود داده‌ها باید به StudentManagementSystem داده بشن نه دیتابیس.
مطمئن نیستم خودت یه مقدار فکر کن ببین اینجوری چیزی نقض نشده؟

2022-08-12 06:40 UTC, smhh22 commented on app/model/entities/Student.cs
> +    public double Average { get; set; }
average رو فکر کنم نباید نگه داری.

2022-08-13 05:46 UTC, abolfazlghalandary requested changes

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/Migrations/20220810065350_school.cs
> +{
پوینت این مایگریشن چیه؟

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/Migrations/20220810082305_mySchool.cs
> +    public partial class mySchool : Migration
naming convention

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/Migrations/20220810084650_test.cs
> +    public partial class test : Migration
.

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/controller/Program.cs
> +        var studentManagementSystem = new StudentManagementSystem { Database = database };
ب نظر من ک اوکیه
نباید کل داده ها لود بشن توی رم

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/controller/Program.cs
> +        userInterface.ShowList<string>(studentManagementSystem.GetNTopStudents(3));
خود کامپایلر تایپشو نمیفهمه؟!

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/model/StudentManagementSystem.cs
> +        return Database.GetStudents().ToList().GroupJoin(Database.GetGrades(), s => s.StudentNumber,
صحبت کردیم سر این
نباید لود شه توی رم
هدف اینه کوئری ساخته بشه بره سمت دیتابیس

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/model/database/PostgresqlDatabase.cs
> +public class PostgresqlDatabase : DbContext, IDatabase
اسم گذاری این کلاس جالب نیس
معمولا باید با context تموم بشه
این لینکو ببین:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0#create-the-database-context

2022-08-13 05:46 UTC, abolfazlghalandary commented on app/model/entities/Grade.cs
> +namespace app.model.entities;
با حروف بزرگ نباید باشه؟!

2022-08-13 05:48 UTC, aliEm2001 commented on app/controller/Program.cs
> +        userInterface.ShowList<string>(studentManagementSystem.GetNTopStudents(3));
Its better to use a constant variable instead of 3.

2022-08-13 06:02 UTC, aliEm2001 approved these changes

2022-08-13 07:18 UTC, Soltaniant commented on app/controller/Program.cs
> +        userInterface.ShowList<string>(studentManagementSystem.GetNTopStudents(3));
نه به نظر. ارور میگیره ازم

2022-08-13 07:41 UTC, Soltaniant commented on app/model/entities/Grade.cs
> +namespace app.model.entities;
اسم فولدرها رو کلا کوچیک نوشتم. کانونشن دقیقی هم پیدا نکردم که بگه ایراد داره یا نه. قبلیاش کوچیک بود. منم کوچیک نوشتم

2022-08-14 05:14 UTC, heidarzade-mh approved these changes

2022-08-14 05:14 UTC, heidarzade-mh commented on app/model/database/SchoolContext.cs
> +            "Host=localhost;Database=databaseNew;Username=postgres;Password=pass");
connectionstring
کانفیگی بشه

2022-08-14 05:26 UTC, closed without merging